# -----------------------------------------------------------------------------
# Control Room module configuration
#   This config allows you to define which other modules should be launched 
#    alongside the control room, how they are launched, and how the control
#    room can interact with them.
#
# 1 Add one module block under [modules.<your-module-name>]
#
# 2 Set kind = 'python' or kind = 'exe', depending on how it should be launched
#
# 3 For python modules, set:
#       - module = '<python.module.entrypoint>'   (runs as: python -m module)
#       - cwd = '<path-to-module-root>'
#   For exe modules, set:
#       - path = '<path-to-executable>'
#
# 4 If your module should be connected via TCP socket, add a
#    [modules.<name>.connection] table with:
#       - type = 'socket'
#       - ip, port
#       - optionally: retry_after_s and max_connect_retries
#    other connection types are not yet supported, but might be in the future
#
# 5 Optional:
#       - args: passed to exe/python modules as command line args
#       - kwargs: passed to python module as --key=value
#       - python_executable: A specific python instance to launch the module with
#       - name: UI/display name (defaults to module key)
#
# 6 Define macros (optional)
#       - Macro commands allow you to execute certain commands directly 
#         from the control room interface
# -----------------------------------------------------------------------------

[modules]
modules_root = '../../'  # optional fallback: if a module has no `cwd`, use modules_root/<module_key>

# Example Python module
[modules.dp-mockup-streamer]
kind = 'python'
name = 'dp-mockup-streamer'
module = 'api.server'
cwd = '../../dp-mockup-streamer'            

# Socket connection settings for this module
[modules.dp-mockup-streamer.connection]
type = 'socket'
ip = '127.0.0.1'
port = 8080
retry_after_s = 1
max_connect_retries = 5

[modules.dp-mockup-streamer.kwargs]
stream_name = 'mockup_EEG_stream'
ip = '127.0.0.1'
port = 8080


# Another Python module
[modules.dp-passthrough]
kind = 'python'
name = 'dp-passthrough'
module = 'api.server'
cwd = '../../dp-passthrough'

[modules.dp-passthrough.kwargs]
ip = '127.0.0.1'
port = 8083

[modules.dp-passthrough.connection]
type = 'socket'
ip = '127.0.0.1'
port = 8083

[macros]

[macros.start_streaming]
    name = 'START_STREAMING'
    description = 'start streaming'
[macros.start_streaming.default_json]
    stream_name = 'mockup_stream'
    date_root = '../'
[macros.start_streaming.cmds]
    # [<target_module>, <PCOMM>, <kwarg_name1 (optional)>, <kwarg_name2 (optional)>]
    com1 = ['dp-mockup-streamer', 'START']
    # com2 = ['dareplane_spoc_recording', 'SET_SAVE_PATH', 'rec_dir=data_root']

[macros.stop_streaming]
    name = 'STOP_STREAMING'
    description = 'start streaming'
[macros.stop_streaming.cmds]
    # [<target_module>, <PCOMM>, <kwarg_name1 (optional)>, <kwarg_name2 (optional)>]
    com1 = ['dp-mockup-streamer', 'STOP']
    # com2 = ['dareplane_spoc_recording', 'SET_SAVE_PATH', 'rec_dir=data_root']
